### ISSUE TITLE
Fine-mapping results not showing

### ISSUE THREAD

**Issue by Zepeng-Mu** [statgen/locuszoom-standalone#10]
Hi,

I am trying to plot my own fine-mapping results to the LocusZoom plot. However, sometimes the fine-mapped region is omitted in the plot, and sometimes it shows fine.

For example, in one region, I could see the coordination is 1.5-1.58 Mb on Chr9. In the output table of fine-mapping regions, there are two SNPs that fall in this region. But these two SNPs (in the same credible set) are not shown in the plot. I also include the example here.

[![Screen-Shot-2019-11-23-at-11-42-17-AM.png](https://i.postimg.cc/yxKkXbfN/Screen-Shot-2019-11-23-at-11-42-17-AM.png)](https://postimg.cc/mzdLT8Wx)
[![Screen-Shot-2019-11-23-at-11-42-25-AM.png](https://i.postimg.cc/NFxLNkVk/Screen-Shot-2019-11-23-at-11-42-25-AM.png)](https://postimg.cc/gLnYj8Gx)

Thank you so much!

**Comment by welchr** [comment]
My guess is that it's dropping all of those extra groups because the default number of finemapping rows is 3 (hence the "6 regions omitted.")

Could you try setting the number of rows to some large number, like: 

```bash
locuszoom <your options here> fmrows=99
```

Does that work?

**Comment by Zepeng-Mu** [comment]
I think it is working now.
Thank you so much!
But when I set `fmrows=99`, the fine-mapping track becomes so wide that the GWAS catalog tracking I am using got pushed out of the page, so I guess I still need to play with the parameter a bit.

**Comment by welchr** [comment]
Good to hear. Some other settings that might help: 

* `height`: set the height of the PDF in inches (default is 7). That would give you a little more space. 
* `gwrows`: set the maximum number of rows for GWAS catalog (default is 3)
* `rfrows`: set the maximum number of rows for genes (default is 10)
